baseURL: https://aafu.pages.dev/
languageCode: en-us
build:
  writeStats: true
params:
  title: aafu theme
  author: Darshan Baral
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: MishaNya
    tagline: (Недо)Python dev
    location: Yoshkar-Ola, Russia
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-telegram
        url: "https://t.me/MishaNyaIsTaken"
        title: Telegram
      - icon: fab fa-vk
        url: "https://vk.com/kr1pt"
        title: VK
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Writing code with AI only python dev. 
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: University Education
        college: Volgatech State University
        dates: 2021-2025
        thesis_title: Software Engineering
      - degree: Ph.D. in AI code writing
        college: OpenAI
        dates: 2022-Present
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: WhisperTranscriberBot
        url: "https://t.me/WhisperTranscriberBot"
        description: Telegram bot that transcribes voice messages in chats
      - title: PocketFriendBot
        description: Future project. Bot that reacts to memes you send him
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Writing code with AI
        skillrating: 90
      - skill: Coming up with new ideas
        skillrating: 80
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Coding
      - hobby: Playing video games
      - hobby: Table tennis
      - hobby: Watching anime
